#!/usr/bin/env python3
"""Generate the per-deployment artifacts from deployments/<name>.yml.

Two things are currently written by hand and can disagree with the SPA's
idea of a deployment:

  deploy/cloudflared/<name>/config.yml   the tunnel's ingress rules
  deploy/access-policies.yml             the Access allowed-lists

Both are pure functions of the deployment file, so generate them. The
cloudflared config keeps its `tunnel:` UUID and `credentials-file:` from
whatever is already committed — those are per-host facts, not derived
ones, and losing them would break the tunnel on the next install.

With the gateway proxying everything (gateway.py --proxy-ws), the
ingress collapses to a single rule: one hostname, one local port,
nothing per-instrument. `--split-ws` emits the pre-Phase-3 shape
instead, where cloudflared routes each /<app>/ws to its own port and the
gateway never sees the instrument WebSocket.

    uv run python tools/generate_deploy_artifacts.py --check   # CI: diff only
    uv run python tools/generate_deploy_artifacts.py --write
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import deployment_config  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
CLOUDFLARED = REPO / "deploy" / "cloudflared"
ACCESS = REPO / "deploy" / "access-policies.yml"


def existing_tunnel(name: str) -> tuple[str, str]:
    """The tunnel UUID and credentials path already committed for `name`."""
    path = CLOUDFLARED / name / "config.yml"
    if not path.exists():
        return ("<tunnel-uuid>", "<path to ~/.cloudflared/<uuid>.json>")
    cfg = yaml.safe_load(path.read_text()) or {}
    return (cfg.get("tunnel", "<tunnel-uuid>"),
            cfg.get("credentials-file", "<credentials>"))


def cloudflared_config(dep_path: Path, split_ws: bool) -> str:
    cfg = deployment_config.resolve(dep_path)
    name, domain, port = cfg["name"], cfg["domain"], cfg["gateway_port"]
    tunnel, credentials = existing_tunnel(name)

    lines = [
        f"# Generated by tools/generate_deploy_artifacts.py from deployments/{name}.yml.",
        "# Edit the deployment file, not this one.",
        "#",
        f"tunnel: {tunnel}",
        f"credentials-file: {credentials}",
        "",
        "ingress:",
    ]

    if split_ws:
        lines += [
            "  # Instrument WebSockets, routed by cloudflared: /<app>/ws -> the",
            "  # app's local WS port. The gateway is not in this path.",
        ]
        for inst in cfg["instruments"]:
            lines += [
                f"  - hostname: {domain}",
                f"    path: ^{inst['ws_path']}$",
                f"    service: http://{inst['host']}:{inst['port']}",
            ]
        lines += [
            "  # Everything else -- the SPA, /config.json, /image/*, /guider/* --",
            "  # is served by the gateway.",
        ]
    else:
        lines += [
            "  # One rule. The gateway owns every path on this hostname: the SPA,",
            "  # /config.json, /<app>/ws (proxied in-process), /image/<app>/ and",
            "  # /guider/<name>/. Adding an instrument does not touch this file.",
        ]

    lines += [
        f"  - hostname: {domain}",
        f"    service: http://localhost:{port}",
        "  # required catch-all",
        "  - service: http_status:404",
        "",
    ]
    return "\n".join(lines)


def access_policies(dep_paths: list[Path]) -> str:
    """Merge the deployment files' `access:` lists into access-policies.yml.

    Deployments that have a file win; every other telescope keeps whatever
    the hand-written file already says, so this can be adopted one
    deployment at a time.
    """
    current = yaml.safe_load(ACCESS.read_text()) if ACCESS.exists() else {}
    telescopes = dict(current.get("telescopes") or {})

    generated = []
    for path in dep_paths:
        cfg = deployment_config.resolve(path)
        dep = deployment_config.load(path)
        if "access" not in dep:
            continue
        telescopes[cfg["name"]] = {"domain": cfg["domain"], "allowed": list(dep["access"])}
        generated.append(cfg["name"])

    header = (
        "# Cloudflare Access policy -- who may control each telescope.\n"
        "#\n"
        "# Synced to Cloudflare by deploy/sync-access-policies.py.\n"
        f"# Entries for {', '.join(generated) or 'no deployments'} are generated from\n"
        "# deployments/<name>.yml by tools/generate_deploy_artifacts.py -- edit the\n"
        "# deployment file for those. The rest are still hand-written here.\n"
        "#\n"
        "# Allowed-entry forms:\n"
        '#   "*@carnegiescience.edu"   whole-domain wildcard -> Access "Emails\n'
        "#                             ending in\" rule. The ONLY wildcard form\n"
        "#                             Cloudflare Access supports.\n"
        '#   "operator@example.org"    exact address -> Access "Email" rule.\n'
        "#\n"
        "# Entries are additive (logical OR). An empty list locks the telescope\n"
        "# down to nobody -- the sync script refuses to push an empty policy\n"
        "# unless --allow-lockout is given.\n\n"
    )
    body = yaml.safe_dump(
        {k: v for k, v in current.items() if k != "telescopes"} | {"telescopes": telescopes},
        sort_keys=False, default_flow_style=False, width=100, allow_unicode=True,
    )
    return header + body


def emit(path: Path, content: str, write: bool) -> bool:
    """Write or diff. Returns True when the file on disk already matches."""
    old = path.read_text() if path.exists() else ""
    if old == content:
        print(f"  {path.relative_to(REPO)}: up to date")
        return True
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"  {path.relative_to(REPO)}: {'updated' if old else 'created'}")
        return True
    print(f"  {path.relative_to(REPO)}: DIFFERS")
    for line in difflib.unified_diff(old.splitlines(), content.splitlines(),
                                     "committed", "generated", lineterm=""):
        print(f"    {line}")
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write the files (default: diff only)")
    ap.add_argument("--check", action="store_true", help="exit non-zero if anything differs")
    ap.add_argument("--split-ws", action="store_true",
                    help="per-instrument WS ingress rules instead of one gateway rule")
    ap.add_argument("deployments", nargs="*", type=Path)
    args = ap.parse_args()

    paths = args.deployments or sorted((REPO / "deployments").glob("*.yml"))
    ok = True
    print("cloudflared:")
    for path in paths:
        name = deployment_config.load(path)["name"]
        ok &= emit(CLOUDFLARED / name / "config.yml",
                   cloudflared_config(path, args.split_ws), args.write)
    print("access policies:")
    ok &= emit(ACCESS, access_policies(paths), args.write)

    if args.check and not ok:
        print("\ngenerated artifacts differ from what is committed", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
